"""Versioned, immutable core types for OpenPhase validation datasets."""

from .aggregation import (
    CrossCheckAgreementSummary,
    ExperimentalAccuracySummary,
    homogeneous_data_class,
    summarize_cross_check_agreement,
    summarize_experimental_accuracy,
)
from .enums import (
    CapabilityUnderTest,
    DataClass,
    PredictionOutcome,
    UncertaintyKind,
    ValidationQuantity,
    ValidationStatus,
)
from .exceptions import (
    HashMismatchError,
    InvariantViolationError,
    MixedDataClassError,
    SchemaVersionError,
    SerializationError,
    UnsupportedValueError,
    ValidationFrameworkError,
)
from .hashing import normalize_sha256, verify_sha256
from .json_values import FrozenJsonObject, JsonScalar, JsonValue
from .models import (
    MOLE_FRACTION_SUM_ABSOLUTE_TOLERANCE,
    SCHEMA_VERSION,
    SUPPORTED_SCHEMA_VERSIONS,
    DatasetIdentity,
    DatasetPin,
    DeclaredTolerance,
    PredictionValue,
    ReferenceDataset,
    ReferenceValue,
    RunMetadata,
    ValidationCase,
    ValidationPrediction,
    ValidationRecord,
    ValidationRun,
    require_supported_schema_version,
)
from .provenance import (
    CompoundIdentity,
    OriginalUnit,
    SourceManifest,
    Uncertainty,
    UnitConversion,
)
from .serialization import (
    decode_reference_dataset,
    decode_validation_record,
    decode_validation_run,
    encode_reference_dataset,
    encode_validation_record,
    encode_validation_run,
)

__all__ = [
    "MOLE_FRACTION_SUM_ABSOLUTE_TOLERANCE",
    "SCHEMA_VERSION",
    "SUPPORTED_SCHEMA_VERSIONS",
    "CapabilityUnderTest",
    "CompoundIdentity",
    "CrossCheckAgreementSummary",
    "DataClass",
    "DatasetIdentity",
    "DatasetPin",
    "DeclaredTolerance",
    "ExperimentalAccuracySummary",
    "FrozenJsonObject",
    "HashMismatchError",
    "InvariantViolationError",
    "JsonScalar",
    "JsonValue",
    "MixedDataClassError",
    "OriginalUnit",
    "PredictionOutcome",
    "PredictionValue",
    "ReferenceDataset",
    "ReferenceValue",
    "RunMetadata",
    "SchemaVersionError",
    "SerializationError",
    "SourceManifest",
    "Uncertainty",
    "UncertaintyKind",
    "UnitConversion",
    "UnsupportedValueError",
    "ValidationCase",
    "ValidationFrameworkError",
    "ValidationPrediction",
    "ValidationQuantity",
    "ValidationRecord",
    "ValidationRun",
    "ValidationStatus",
    "decode_reference_dataset",
    "decode_validation_record",
    "decode_validation_run",
    "encode_reference_dataset",
    "encode_validation_record",
    "encode_validation_run",
    "homogeneous_data_class",
    "normalize_sha256",
    "require_supported_schema_version",
    "summarize_cross_check_agreement",
    "summarize_experimental_accuracy",
    "verify_sha256",
]
